### ISSUE TITLE
Improve low-mass synthetic centrals

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#14]
We model synthetic low-mass galaxies in cosmoDC2 by sprinkling in subhalos  until dn/dMpeak, the subhalo peak mass function, is a perfect power law down to a very low subhalo mass completeness limit. Then we paint stellar masses onto these fake subhalos using log-normal scatter about a power law approximation to the median relation `<M*|Mpeak>` in UniverseMachine, and then otherwise treat them like ordinary galaxies. 

We have two treatments for the spatial positions of these galaxies, a `centrals` implementation, and a `satellites` implementation; the former distributes these galaxies at spatially random points within each populated healpixel, the latter distributes them according to a spherically symmetric NFW profile centered at a randomly chosen host halo. These two implementations give nice bracketing cases for the density-dependence of blending, which will occur at much higher rates in the `satellites` implementation relative to the `centrals` implementation, even though these two implementations are designed to produce identical luminosity functions, by construction. 

Currently, our centrals implementation falls short of achieving the desired number of additional galaxies to complete the power law. This failure happens for two reasons:
1. We only generate enough fake galaxies to double the size of the mock, as opposed to generating enough to hit the desired dn/dmag. This was done to reduce the memory load for short term purposes and should be trivial to fix. 
2. The fake centrals are distributed randomly within a rectangle enclosing the healpixel, so some galaxies are lost due to masking. A sketch of the solution to this is demonstrated in the following gist: 
https://gist.github.com/aphearin/59a23dae6843c5d4674a56d523535001

@evevkovacs - can you take a look at the gist and try to implement the improvement?

**Comment by aphearin** [comment]
In `cosmoDC2_v0.4`, we decided to use the satellite treatment of synthetic low-mass galaxies, rather than hold up the pipeline for this fix. Based on [this round of DESCQA tests](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-10_1&catalog=cosmoDC2_v0.4), our current satellites implementation performs well on the dn/dmag and dn/dz tests, which are the primary tests this synthetic population was designed for; here is an example plot for convenience. 

![hsc_dndmag](https://user-images.githubusercontent.com/6951595/43982616-493d1c1a-9cbc-11e8-8af3-c662e0d21021.png)

Based on this result, I think we should just use the `satellites` treatment for the final cosmoDC2 release. We can improve the implementation of the centrals after the cosmoDC2 release. Before I move this issue to `post-cosmoDC2` milestone, tagging @rmjarvis and @rmandelb to see whether they have an opinion concerning our final choice for the implied density-dependence of the blending.

**Comment by rmandelb** [comment]
First, just commenting on the plot: The number counts look very good!  Is it similar in other bands? 
 While we are not quite comparing apples to apples (because the HSC curve is after blending and other observational effects, and the other is before it), it is really nice to see this agreement, and hopefully the observed counts in the sims will be similar.

Now to answer your actual question: previous work suggests that blending in a survey the depth of LSST is dominated by pairs at different redshifts, so that implies that in real life the blending is mildly but not very density-dependent (except for in the cores of massive clusters which are a small fraction of the sky indeed).  So - for this effect that you're describing to change that balance between blends at the same vs. different redshifts in a significant way, my guess is that you'd have to be modifying the small-scale galaxy correlation function in a way that would probably screw up other tests in DESCQA... like do we have a test of the angular clustering as a function of scale in magnitude bins, or something that would pick up an overly prominent 1-halo term?   The redmapper richness-mass relation would also be a good test for this, unless these satellites are sufficiently faint that they wouldn't pass the luminosity cut to be caught by redmapper.  Essentially I find it hard to imagine that we have no clustering or cluster-related tests that would catch the use of the `satellite` treatment being a serious problem.

Curious to hear @rmjarvis 's take.

**Comment by aphearin** [comment]
@rmandelb - these are *very* low-mass satellites, dwarf galaxy mass with all stellar masses M*<10^8, following a power-law down to 10^6; so, extremely sparse observational data on the statistics of this population, I should have provided that context earlier in this issue. In DESCQA, there are no two-point constraints in this regime, and these galaxies have zero impact on cluster richness as well, simply because they are so faint. These galaxies *do* impact the very faint-end of the luminosity function probed by HSC (which, yes, looks good in other bands as well, another plot below in the y-band, see the above DESCQA link for the full gamut). 

![hsc_y](https://user-images.githubusercontent.com/6951595/43985772-b6e777f2-9ccf-11e8-8f08-6e535c2bc2a6.png)

**Comment by evevkovacs** [comment]
Here are some more details:
 For the baseline catalog with centrals there are still some problems:
There are some weird high values for the redshifts (possibly interpolation failures), and the stellar-mass distribution still has some bimodality.
Test claims that halo_ids are not unique but galaxy_id's are ok.
![sm_cen](https://user-images.githubusercontent.com/7797837/43993678-18ed89e6-9d57-11e8-8601-204ecd6ab481.png)
![mag_cen](https://user-images.githubusercontent.com/7797837/43993681-2a9fddba-9d57-11e8-9f8c-100087570fb6.png)
![redshift_cen](https://user-images.githubusercontent.com/7797837/43993687-399bad76-9d57-11e8-8c9f-f5d885155c78.png)

We are not planning to use this method for the image sims, but these issues should be fixed.

3) For the baseline catalog with satellites, the redshift and stellar-mass distributions look ok. Test claims that halo_ids are
unique but galaxy_ids are not.

**Comment by rmandelb** [comment]
Yes, there are clearly some kinks to be worked out with the centrals option, but if you're not planning to use that for the cosmoDC2 version that feeds into image sims, I can imagine that fixing that is lower priority.

For the satellites option, what does "redshift and stellar mass distributions look ok" mean - just a lack of extreme outliers in the former and bimodality in the latter?  Or is the redshift distribution relatively smooth / does it satisfy basic sanity checks, as well?

**Comment by rmandelb** [comment]
Definitely much better than the satellite model.  I'm not finding the redshift distribution fluctuations very worrisome.  Thanks for the plots!

**Comment by evevkovacs** [comment]
@rmandelb Maybe you misspoke, but just to be clear, the plots in my last comment were for the satellite model NOT the central model.

**Comment by rmandelb** [comment]
Yes, I just mistyped, sorry.

**Comment by evevkovacs** [comment]
With the implementation of the improved loop to make sure that all the simulated synthetic central galaxies end up inside the healpixel, the bimodality in the stellar-mass and Magnitude distributions has gone away. (The issue was that not enough centrals were being saved to "fill in" the expected distributions at low M*) See [these distributions](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-15_5&test=readiness_baselineDC2&right=2018-08/2018-08-15_5/readiness_baselineDC2/baselineDC2_v0.4_cens_oldcolor/), from a readiness test on baseDC2.
