### ISSUE TITLE
Infinite magnitudes of some galaxies in halos with `target_halo_fof_halo_id`=0

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#39]
@dkorytov has discovered that some of the galaxies produced by the current master branch of the code are being assigned infinite values of `restframe_extincted_sdss_abs_magr`. These galaxies are presumed to be synthetic, though we are not sure; these galaxies appear at many different redshifts, and they all seem to have `target_halo_fof_halo_id`=0. This bug happens *prior* to Dan's matchup code, so the problem lies somewhere in the restframe color-assignment phase. @evevkovacs and I will look closely at this and give it a high priority to resolve asap.

**Comment by evevkovacs** [comment]
This bug only appeared for the synthetic galaxies. It was caused by galaxies being assigned zero stellar mass. Fixing the stellar-mass problem fixed the infinite magnitude problem. See [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-15_5&test=readiness_baselineDC2&right=2018-08/2018-08-15_5/readiness_baselineDC2/baselineDC2_v0.4_cens_oldcolor/) and note that the faction of infinite values in log(M*) and Magnitudes is now zero.
