### ISSUE TITLE
discreteness effects in Mhost-dependence of red sequence colors

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#6]
As pointed out by @erykoff and @chto, in protoDC2 the observed colors of red sequence galaxies have sharp dependence upon host halo mass that is not seen in DES data. In principle, as discussed with @dkorytov, this can easily be rectified by relaxing the Mhost-dependence in the red sequence color matchup. In practice, this change may significantly impact the population statistics, and so this needs to be explicitly tested in a small-volume cosmoDC2 run.

**Comment by erykoff** [comment]
Just to add some additional info to this, the current catalogs produce red galaxies of sharply different colors when they are in halos with m>3e13 or when they are in lower mass halos.  This would mean that clusters on their own would be fine, but the cluster red sequence could not be used for redMaGiC red-galaxy selection (which assumes that red galaxies look like red galaxies no matter where they are), and would conversely mean that photo-z based cluster finders would fail because photo-zs trained on numerous spectroscopic galaxies in halos of m<~1e13 would not work for cluster members.  

Similarly, a CMASS-type selection would not properly select galaxies with a host mass above the threshold.  

Of course, we want to maintain that the red fraction is a function of mass, but not that the colors of the red galaxies themselves are a function of mass (excepting the fact that more massive halos tend to host more luminous galaxies which tend to be redder).

**Comment by dkorytov** [comment]
I've updated the model to have a soft turn on for matching observed red sequence colors start at 12.5 (0%) to 13.5 (100%) 

**Before** 
![screenshot from 2018-08-09 16-31-14](https://user-images.githubusercontent.com/25048061/43927281-a4454eea-9bf2-11e8-92ef-11339d9b5374.png)


**Now** 
![screenshot from 2018-08-09 16-33-30](https://user-images.githubusercontent.com/25048061/43927290-aa0f0b90-9bf2-11e8-957e-69eb175ee7f9.png)

**Comment by erykoff** [comment]
Definitely looks cleaner.  Is it possible to make the plots with matched axes?
Also, what's with the population of much-redder-than-the-red-sequence centrals?

**Comment by aphearin** [comment]
@erykoff - do you mean the very tiny population of red galaxies at very low halo mass?

**Comment by erykoff** [comment]
At low halo mass there's a tiny population that hits the upper limit, and at 12-13 there are some that are sitting at g-r ~ 2, while the bulk are at 1.5.

**Comment by aphearin** [comment]
@erykoff - I just quickly checked and I find that, for reasonably bright galaxies galaxies (brighter than Mr<-18 in the restframe), about 5-10% of them have observed colors that are redder than the cluster red sequence. I think I understand why you ask about this: in a mock that is optimum for redMaPPer science targets, this number should be 0%. The root issue is #27: these galaxies are red sequence field galaxies, so they have the same restframe colors as the cluster red sequence, but not necessarily identical SED characteristics. 

While properly resolving #27 is beyond the scope of cosmoDC2, one thing we could try is applying an additional cut on the Galacticus library before conducting the matchup (@erykoff - let me know if you are following or want me to be more explicit). So, for example, at each redshift, before running his matchup code, @dkorytov could throw away any Galacticus galaxy with observed colors greater than 2sigma beyond the mean red sequence colors observed in DES. I'd be a little worried that this will introduce a sharp feature in color-redshift space, so this solution may be worse than the problem, so do let me know if you have other suggestions for modifications we can try along these lines.

**Disclaimer**: We can certainly give a trial run to this additional cut to see whether implementing it has unwanted consequences for other tests. If there are no unwanted side effects, then it would be relatively easy to incorporate this improvement into cosmoDC2. But since we're at the very final calibration stage, we can't give any guarantees that this or other redMaPPer-motivated modifications will make it into cosmoDC2.

**Comment by erykoff** [comment]
Okay, so this is due to a SED mismatch; I thought it was something to do with the host dust (because these galaxies should have very very low host dust, but I don't think that's a requirement in the generation of the catalog).  I don't believe this is a dealbreaker for now; it certainly will make things perform less well, but not catastrophically so.  I am thinking about future improvements and also "what can make a galaxy redder than the red sequence?"

I don't think that putting in a cut based on DES red sequence colors would be a good idea.  Aside from filter transformation issues, I don't mean to say that the DES colors are "truth" in any way.  They are merely a helpful reference to what redMaPPer is finding in DES, and a reasonable model of my expectations.  And practically speaking, redMaPPer doesn't care what the colors are, aside from the fact that there's an assumption that there is a red sequence that's reasonably tight scatter, reasonably distinct from the blue cloud, and has a ~linear color/magnitude relation.  

Instead, I think that looking at these plots is helpful in diagnosing underlying issues; this pair already shows that things are looking much more reasonable.  Though the redder-than-the-red-sequence galaxies stand out.  You can also see the hint of the mass dependence and other discrete features.  How bad these are in practice, of course, will (hopefully) be tested by our validation tests.
