### ISSUE TITLE
Magnitude Cuts for 5000 sq. deg. cosmoDC2

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/cosmodc2#65]
This issue is about determining what magnitude cuts (if any) it is possible to make for the final 5000 sq. deg. cosmoDC2 catalog. CosmoDC2_v1.0, which is being used for image simulations, has many very faint galaxies that were included for WL systematic studies. If it can be determined that some fraction of these galaxies are not relevant for the science to be obtained from the full catalog, it would be advantageous to minimize the use of resources by discarding them early in the production pipeline.

**Comment by rmandelb** [comment]
Just to record some factors relevant to "science impact" based on today's DC2 telecon plus my own thoughts:

* The v1.0 that was used for image simulations will remain as-is.  As a result, studies that involve use of the image sims (with fainter galaxies below the flux limit) matched against the v1.0 extragalactic catalog used to produce the image sims will self-consistently have the fainter galaxies in both.

* The science impact discussion in this issue should therefore focus on studies that will exclusively use the extragalactic catalog.

* We should bear in mind that while the fainter galaxy populations are there in *roughly* the right abundance (see notes on how this was ascertained [here](https://github.com/LSSTDESC/DC2-production/issues/263#issuecomment-421207430)), there is some (very) limited evidence that their colors might not be quite right, and we have no means of validating their clustering, sizes, etc.  So use of galaxy populations below a certain magnitude  limit for some science comes at considerable risk. We did use these faint populations in the image sims because we just needed them to exist as roughly (within factor of 2) the right number of faint blobs with properties that are not outright insane, so as to have suitably challenging blending between the bright galaxies we'll use for science and faint galaxies. This meant we could set a pretty low bar in terms of the realism of the faint population.  Using them for other purposes requires us to factor in the inherent uncertainties in the properties of the faint sample plus their potential irrelevance to a real LSST analysis (i.e., an actual analysis in LSST will have to correspond to some reasonably-selected sample from the images, not including the marginal detections that are inflating these catalog sizes).  If we decide that these analyses cannot  use galaxies below a certain magnitude limit given both of those considerations, then it makes sense to exclude those populations from the 5000 sq deg catalog so that the file read-in and subsequent calculations will be more efficient for everybody.

* Also note that unlike for the image sims, regenerating the extragalactic catalogs with the faint populations later on is more feasible if a need for populations that were initially excluded is identified.  It's not zero work, either, so there would have to be a solid justification.  (Producing such a justification could involve use of the smaller-area version of cosmoDC2 that was used for the image sims and that includes the faint population.)

**Comment by evevkovacs** [comment]
Discussion has been moved to: [DC2_production issue #336](https://github.com/LSSTDESC/DC2-production/issues/336)
